# -*- coding: utf-8 -*-
"""2주차 공통해 구하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huqIYpz-Eic3dJBChmelwjvkbo9qfgXG
"""

import numpy as np

A = np.array([
    [2, 1],
    [2, -1],
    [1, -2]
],dtype = float)

b = np.array([3, 1, -1], dtype=float)

solution, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

x1, x2 = solution

print(f"x1 = {x1:.6f}")
print(f"x2 = {x2:.6f}")

print("A @ solution =", A @ solution)
print("b =", b)

if np.allclose(A @ solution, b):
    print("공통해가 존재함")
    print(f"공통해: ({x1:.0f},{x2:.0f})")
else:
    print("공통해가 존재하지 않음")